# action.yml
name: 'Echidna'
description: 'Run echidna-test'
inputs:
  files:
    description: 'Files to analyze'
    required: true
  contract:
    description: 'Solidity contract to test'
    required: false
  config:
    description: 'Config file'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
